
########################################################################################################################
# General ESPHome config                                                                                               #
########################################################################################################################
esphome:
  name: window_opener
  platform: ESP8266
  board: d1 # optional, only affects pin layout
  # on boot: close both relays (so we don't have any shenanigans when power cycling)
  on_boot:
    then:
      - switch.turn_off: open_relay
      - switch.turn_off: close_relay

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret wifi_static_ip
    gateway: !secret wifi_gateway
    subnet: !secret wifi_subnet

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret wifi_fallback_ap_ssid
    password: !secret wifi_fallback_ap_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

########################################################################################################################
# I/O                                                                                                                  #
########################################################################################################################
# Notes:
# - The switching logic below contains some extra checks and actions to ensure (and double ensure) that both relays
#   are never engaged at the same time, as this can cause a short-circuit in the linear actuator that opens the window.
# - If homeassistant changes the relay states while a button is pressed, releasing the button will automatically cancel
#   the signal coming from homeassistant. This is a good safety.

# RELAYS
switch:
  - platform: gpio
    name: "Open Relay"
    id: open_relay
    pin: D10
    # if we turn on this relay, automatically turn off the other one.
    # Required for when switching from home-assistant.
    on_turn_on:
      - then:
          - switch.turn_off: close_relay

  - platform: gpio
    name: "Close Relay"
    id: close_relay
    pin: D8
    on_turn_on:
      - then:
          - switch.turn_off: open_relay

# BUTTONS
binary_sensor:
  - platform: gpio
    name: "Open Button"
    pin: D2
    on_press:
      then:
        # turn off the other relay, but double check (=if) before turning on this one to ensure we don't turn them
        # on at the same time.
        - switch.turn_off: close_relay
        - if:
            condition:
              switch.is_off: close_relay
            then:
              - switch.turn_on: open_relay
   # on_release: turn both relays off, this is just an extra safety to avoid having both relays on at the same time.
    on_release:
      then:
        - switch.turn_off: open_relay
        - switch.turn_off: close_relay

  - platform: gpio
    name: "Close Button"
    pin: D4
    on_press:
      then:
        - switch.turn_off: open_relay
        - if:
            condition:
              switch.is_off: open_relay
            then:
              - switch.turn_on: close_relay
    on_release:
      then:
        - switch.turn_off: open_relay
        - switch.turn_off: close_relay
